# .pre-commit-hooks.yaml
- id: check-inline-styles
  name: Check Inline Styles
  description: This hook checks for inline styles in HTML files.
  entry: check_inline_styles.py
  language: python
  files: \.html$